"""empty message

Revision ID: 08de75090048
Revises: 154a68fc0a30
Create Date: 2023-06-17 16:48:11.131498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08de75090048"
down_revision = "154a68fc0a30"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointments", sa.Column("start_time", sa.Time(), nullable=True)
    )
    op.add_column(
        "appointments", sa.Column("end_time", sa.Time(), nullable=True)
    )
    op.drop_constraint(
        "fk_appointments_users_id_doctor", "appointments", type_="foreignkey"
    )
    op.drop_column("appointments", "doctor")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointments",
        sa.Column("doctor", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "fk_appointments_users_id_doctor",
        "appointments",
        "users",
        ["doctor"],
        ["id"],
    )
    op.drop_column("appointments", "end_time")
    op.drop_column("appointments", "start_time")
    # ### end Alembic commands ###
