"""empty message

Revision ID: 154a68fc0a30
Revises: 4ff1251ddee5
Create Date: 2023-06-17 14:43:52.211093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154a68fc0a30'
down_revision = '4ff1251ddee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_schedules_date_user', 'schedules', ['date', 'user'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_schedules_date_user', 'schedules', type_='unique')
    # ### end Alembic commands ###
