"""empty message

Revision ID: 23e80f61c310
Revises: 0e2b8950f271
Create Date: 2023-03-30 17:23:05.346735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e80f61c310'
down_revision = '0e2b8950f271'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
