"""empty message

Revision ID: 24f1d8dbe0eb
Revises: 4aa92573553a
Create Date: 2023-06-16 17:04:26.070934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f1d8dbe0eb'
down_revision = '4aa92573553a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
