"""empty message

Revision ID: 2d17b10f78cb
Revises: 23e80f61c310
Create Date: 2023-06-04 12:19:57.005981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d17b10f78cb'
down_revision = '23e80f61c310'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('status', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'status')
    # ### end Alembic commands ###
