"""empty message

Revision ID: 4aa92573553a
Revises: 77fca6b9d70d
Create Date: 2023-06-14 22:36:57.952019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa92573553a'
down_revision = '77fca6b9d70d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
