"""empty message

Revision ID: 76f015bffeb1
Revises: f2b8d5783e7f
Create Date: 2023-06-20 23:43:09.433445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f015bffeb1'
down_revision = 'f2b8d5783e7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('xrays', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('xrays', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
