"""empty message

Revision ID: 77fca6b9d70d
Revises: 8467d90e8746
Create Date: 2023-06-14 22:13:43.881710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fca6b9d70d'
down_revision = '8467d90e8746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
