"""empty message

Revision ID: 8467d90e8746
Revises: b20fb7cc89ff
Create Date: 2023-06-14 21:55:47.850037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8467d90e8746'
down_revision = 'b20fb7cc89ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
