"""empty message

Revision ID: 9d4d965d306b
Revises: 24f1d8dbe0eb
Create Date: 2023-06-16 17:14:09.777840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4d965d306b'
down_revision = '24f1d8dbe0eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
