"""empty message

Revision ID: a4e5683b00b2
Revises: f603db8ff0b0
Create Date: 2023-03-30 16:38:13.078641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e5683b00b2'
down_revision = 'f603db8ff0b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
