"""empty message

Revision ID: a7ea6716c95d
Revises: ad18ac56adb5
Create Date: 2023-06-17 12:17:37.120281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ea6716c95d'
down_revision = 'ad18ac56adb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
