"""empty message

Revision ID: ad18ac56adb5
Revises: 9d4d965d306b
Create Date: 2023-06-17 12:11:34.983172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad18ac56adb5'
down_revision = '9d4d965d306b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profit_loss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=True),
    sa.Column('total_expenses', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('paid_amount', sa.Integer(), nullable=False),
    sa.Column('desctiption', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['admin'], ['users.id'], name='fk_accounting_users_id_admin'),
    sa.ForeignKeyConstraint(['patient'], ['users.id'], name='fk_accounting_users_id_patient'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['admin'], ['users.id'], name='fk_loss_users_id_admin'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loss')
    op.drop_table('accounting')
    op.drop_table('profit_loss')
    # ### end Alembic commands ###
