"""empty message

Revision ID: b20fb7cc89ff
Revises: f3a240da4a92
Create Date: 2023-06-14 20:27:34.649979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20fb7cc89ff'
down_revision = 'f3a240da4a92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
