"""empty message

Revision ID: c6970f473e04
Revises: 297e52ed70f7
Create Date: 2023-06-18 11:26:14.521096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6970f473e04'
down_revision = '297e52ed70f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
