"""empty message

Revision ID: f2b8d5783e7f
Revises: e75c72afb20b
Create Date: 2023-06-18 11:27:16.155846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b8d5783e7f'
down_revision = 'e75c72afb20b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_med_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient', sa.Integer(), nullable=False),
    sa.Column('disease', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=False),
    sa.Column('doctor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor'], ['users.id'], name='fk_e_med_card_users_id_doctor', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient'], ['users.id'], name='fk_e_med_card_users_id_patient', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('e_med_card')
    # ### end Alembic commands ###
