"""empty message

Revision ID: f3a240da4a92
Revises: 7bcd0bc196df
Create Date: 2023-06-12 15:04:36.177259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a240da4a92'
down_revision = '7bcd0bc196df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_med_card', sa.Column('patient', sa.Integer(), nullable=False))
    op.add_column('e_med_card', sa.Column('doctor', sa.Integer(), nullable=False))
    op.drop_constraint('fk_e_med_card_users_id_user', 'e_med_card', type_='foreignkey')
    op.create_foreign_key('fk_e_med_card_users_id_doctor', 'e_med_card', 'users', ['doctor'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_e_med_card_users_id_patient', 'e_med_card', 'users', ['patient'], ['id'], ondelete='CASCADE')
    op.drop_column('e_med_card', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_med_card', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_e_med_card_users_id_patient', 'e_med_card', type_='foreignkey')
    op.drop_constraint('fk_e_med_card_users_id_doctor', 'e_med_card', type_='foreignkey')
    op.create_foreign_key('fk_e_med_card_users_id_user', 'e_med_card', 'users', ['user'], ['id'], ondelete='CASCADE')
    op.drop_column('e_med_card', 'doctor')
    op.drop_column('e_med_card', 'patient')
    # ### end Alembic commands ###
