"""empty message

Revision ID: f603db8ff0b0
Revises: ec08d97db3a5
Create Date: 2023-03-30 16:26:19.924101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f603db8ff0b0'
down_revision = 'ec08d97db3a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_schedules_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor', sa.Integer(), nullable=True),
    sa.Column('schedule', sa.Integer(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor'], ['users.id'], name='fk_appointments_users_id_doctor'),
    sa.ForeignKeyConstraint(['patient'], ['users.id'], name='fk_appointments_users_id_patient'),
    sa.ForeignKeyConstraint(['schedule'], ['schedules.id'], name='fk_appointments_schedules_id_schedule'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_table('schedules')
    # ### end Alembic commands ###
